KATOM, KUNARY, KBINARY,\
    KCOLO, KCOLC, KQ, KSEMI,\
    KFOR, KFROM, KSET, KGET,\
    KAT, KAS, KCOMM, KEQ, KMTFD,\
    KMTFC, KDFN, KKW, KSTR, KINT,\
    KTHT, KCLS, CMNT, HEDR, AUGA,\
    KCLN, TMPRL, BRO, BRC, TMPA, TMPS,\
    KQUIT, *_    = range(0x00, 0xF0)
CODE_MAP = {
    KATOM: 'ATOM', KQUIT: b'STOP SIGNAL',
    KUNARY: "UNARY OPERATOR",
    KBINARY: "BINARY OPERATOR",
    KCOLO: "PARENTHESES (OPEN)", KCOLC: "PARENTHESES (CLOSE)",
    BRO: "SQUARE BRACKET (OPEN)", BRC: "SQUARE BRACKET (CLOSE)",
    KSEMI: "SEMICOLON", KQ: "QUESTION MARK", KSET: "'SET' KEY WORD", KGET: "'GET' KEYWORD",
    KFOR: "'FOR' KEYWORD", KFROM: "'FROM' KEYWORD", KAS: "'AS' KEYWORD", KAT: "'AT' KEYWORD",
    KDFN: "VARIABLE DEFINITION", KCOMM: "COMMA", KEQ: "ASSIGNMENT OPERATOR", KKW: "GENERIC KEYWORD",
    KSTR: "STRING", KINT: "INTEGER", KTHT: "THOUGHT", KCLS: "CLASS", HEDR: "HEADER DIRECTIVE",
    AUGA: "AUGMENTED ASSIGNMENT", KCLN: "COLON", KMTFD: "MOTIF REGISTRATION", KMTFC: "MOTIF REDIRECTIVE"
}
ANY = {KATOM, KTHT, KINT, KSTR}
FAITHFUL = 10
# ERR KEY REFERENCE
# 0xA_ = MTF
# 0xB_ = EXPR
# 0x